// Generated by CoffeeScript 1.10.0
(function() {
  var AST, Loader;

  AST = require('./ast');

  Loader = (function() {
    function Loader(env) {
      if (env == null) {
        env = AST.baseEnv;
      }
      if (!(this instanceof Loader)) {
        return new Loader();
      }
      Object.defineProperty(this, 'env', {
        value: env,
        enumerable: false,
        writable: false
      });
    }

    Loader.prototype.load = function(obj) {
      var key;
      key = this.key(obj);
      if (Loader.prototype.hasOwnProperty(key)) {
        return this[key](obj);
      } else {
        throw new Error("Loader.load:unknown_type: " + obj.type);
      }
    };

    Loader.prototype.key = function(obj) {
      return '_' + obj.type;
    };

    Loader.prototype._integer = function(obj) {
      return this.env.get('integer')(obj.value);
    };

    Loader.prototype._float = function(obj) {
      return this.env.get('float')(obj.value);
    };

    Loader.prototype._boolean = function(obj) {
      return AST.get('boolean')(obj.value);
    };

    Loader.prototype._string = function(obj) {
      return AST.get('string')(obj.value);
    };

    Loader.prototype._date = function(obj) {
      return AST.get('date')(obj.value);
    };

    Loader.prototype._null = function(obj) {
      return AST.get('null')();
    };

    Loader.prototype._undefined = function(obj) {
      return AST.get('undefined')();
    };

    Loader.prototype._symbol = function(obj) {
      return AST.get('symbol')(obj.value);
    };

    Loader.prototype._regex = function(obj) {
      return AST.get('regex')(obj.value);
    };

    Loader.prototype._parameter = function(obj) {
      var name;
      name = typeof obj.name === 'string' ? AST.get('symbol')(obj.name) : this.load(obj.name);
      return AST.get('param')(name);
    };

    Loader.prototype._array = function(obj) {
      var item, items;
      items = (function() {
        var i, len, ref, results;
        ref = obj.items;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          item = ref[i];
          results.push(this.load(item));
        }
        return results;
      }).call(this);
      return AST.get('array')(items);
    };

    Loader.prototype._object = function(obj) {
      var key, keyvals, val;
      keyvals = (function() {
        var ref, results;
        ref = obj.properties;
        results = [];
        for (key in ref) {
          val = ref[key];
          results.push([AST.get('symbol')(key), this.load(val)]);
        }
        return results;
      }).call(this);
      return AST.get('object')(keyvals);
    };

    Loader.prototype._member = function(obj) {
      var head, key;
      head = this.load(obj.head);
      key = this.load(obj.key);
      return AST.get('member')(head, key);
    };

    Loader.prototype._unary = function(obj) {
      var op, rhs;
      op = this.load(obj.op);
      rhs = this.load(obj.rhs);
      return AST.get('unary')(op, rhs);
    };

    Loader.prototype._binary = function(obj) {
      var lhs, op, rhs;
      op = this.load(obj.op);
      lhs = this.load(obj.lhs);
      rhs = this.load(obj.rhs);
      return AST.get('binary')(op, lhs, rhs);
    };

    Loader.prototype._if = function(obj) {
      var cond, elseExp, thenExp;
      cond = this.load(obj.cond);
      thenExp = this.load(obj.then);
      elseExp = this.load(obj["else"]);
      return AST.get('if')(cond, thenExp, elseExp);
    };

    Loader.prototype._block = function(obj) {
      var body, exp;
      body = (function() {
        var i, len, ref, results;
        ref = obj.body || [];
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          exp = ref[i];
          results.push(this.load(exp));
        }
        return results;
      }).call(this);
      return AST.get('block')(body);
    };

    Loader.prototype._procedureCall = function(obj) {
      var arg, args, proc;
      proc = this.load(obj.proc);
      args = (function() {
        var i, len, ref, results;
        ref = obj.args || [];
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          arg = ref[i];
          results.push(this.load(arg));
        }
        return results;
      }).call(this);
      return AST.get('procedureCall')(proc, args);
    };

    Loader.prototype._procedure = function(obj) {
      var arg, args, body, name;
      name = obj.name ? this.load(obj.name) : null;
      args = (function() {
        var i, len, ref, results;
        ref = obj.args || [];
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          arg = ref[i];
          results.push(this.load(arg));
        }
        return results;
      }).call(this);
      body = this.load(obj.body);
      return AST.get('procedure')(name, args, body);
    };

    Loader.prototype._define = function(obj) {
      var name, value;
      name = this.load(obj.name);
      value = this.load(obj.value);
      return AST.get('define')(name, value);
    };

    Loader.prototype._assign = function(obj) {
      var name, value;
      name = this.load(obj.name);
      value = this.load(obj.value);
      return AST.get('assign')(name, value);
    };

    return Loader;

  })();

  AST.Loader = Loader;

  AST.load = function(obj) {
    var loader;
    loader = Loader();
    return loader.load(obj);
  };

  module.exports = Loader;

}).call(this);
